### ISSUE TITLE
Duplicate topics

### ISSUE THREAD

**Issue by TAToolbox** [TAToolbox/class-helper#1]
If a `topic` string appears more than once in the lesson plans, Class Helper will mirror the changes to all matches while only showing the first occurrence in `stdout`.

**Example**:
```
What's the topic this week?: python
03-Python? [Y/N] y
```
will run on `03-Python` and `06-Python-APIs`

**Workaround**:
Use the number label for these weeks.  For example: `03` instead of `python`

**Comment by trivial-vector** [comment]
fixed with a `-quit` flag on the find statement
